### ISSUE TITLE
Followed hashtags feed

### ISSUE THREAD

**Issue by jcrabapple** [LucasGGamerM/moshidon#11]
**Is your feature request related to a problem? Please describe.**
The advanced web interface has the ability to follow hashtags and also pin them in their own columns. This doesn't exist in most mobile apps. 

**Describe the solution you'd like**
I would like the ability to view a feed of all my followed hashtags and unfollow them if I want. 

**Describe alternatives you've considered**
I think Fedilab has created their own version of pinned hashtag feeds.

**Comment by LucasGGamerM** [comment]
You can view your followed hashtags on your profile, in the top right corner. I don't know how to proceed with the hashtags only timeline. Anyhow, I will see what I can do about it

**Comment by jcrabapple** [comment]
Oh thanks I didn't realize that button was there. Thanks for looking into
the hashtag timeline.

**Comment by LucasGGamerM** [comment]
Its fixed with 87. Though there isnt yet a button for 'all' the hashtags you follow, there is a list of them all in the home screen.

**Comment by wolfyjade** [comment]
hey, so, first of all, sorry for replying to such an old (and already closed) issue here, but I'm genuinely wondering if it'd be possible to add a separate timeline to the home timelines where one can see posts from _all_ followed hashtags, without having to go through the list of the followed hashtags and catch up on all of them separately (which is already starting to get annoying since I'm following 16 of them by now-)
