### ISSUE TITLE
Voting on polls inside CustomLocalTimelines doesnt work

### ISSUE THREAD

**Issue by LucasGGamerM** [LucasGGamerM/moshidon#122]
Voting on polls inside custom local timelines still does not work, I need to work on it later. Might be related to #110

**Comment by FineFindus** [comment]
The issue is that the `poll.id` is local to the server. Because the `status` with the poll is loaded from a different server, the poll IDs won't match, the loaded ID will point to the wrong poll, or nothing at all.

The solution is probably to reload the poll and get the correct ID from the home server. I have a fix ready, but I think there could be a nicer implementation.

**Comment by LucasGGamerM** [comment]
Shall be closed with commit e3f445cbeda6ba7a46f52a0577f6523bb45d1929
