### ISSUE TITLE
Option to enable tree/nested style comment/reply view

### ISSUE THREAD

**Issue by librenyaa** [LucasGGamerM/moshidon#208]
**Is your feature request related to a problem? Please describe.**
It is difficult to follow along on long discussions on posts that branch into multiple conversations between many different users.

**Describe the solution you'd like**
An option to enable tree style comment/reply view

**Describe alternatives you've considered**
N/A

I'm not sure how difficult this is to implement, but it would be a major QOL improvement if possible

**Comment by LucasGGamerM** [comment]
I think @sk22 did something to address that on Megalodon, and I already merged it, so I believe its fixed

**Comment by sk22** [comment]
i mean it's not a tree view - essentially, i just disabled the dividers for posts in threads which are replies to each other, so that divider lines mean that the next post isn't part of that thread anymore - but it serves a similar purpose ^^

i actually briefly experimented with indenting the replies according to their reply "depth" in a given thread view context. it would've worked, but i figured it'd be too much of an effort to implement, and even harder to make it look good; actually, i wouldn't know if this would even be compatible with the app's design at all.. so i didn't do that :')
